#We need less code, and something that might work in a lot of cases that saves us time..

#Add more here as needed

#Use forward slashes for the subdir whether on windows or a unix based system.
    
OMNI:

  ONE_MIN_RESOLUTION:

    subdir : "{$YEAR}"
    file_glob : "omni_hro2_1min_{$YEAR}{$MONTH}*.cdf"
    url : "https://spdf.gsfc.nasa.gov/pub/data/omni/omni_cdaweb/hro2_1min/{$YEAR}/"
    variables: 
      time_variables:
        Epoch: 0
      time_dependent:
        BZ_GSM : 0
        AE_INDEX: 0
        Vz: 0
        #Machine learning model needed these...
        flow_speed : 0
        proton_density : 0
        SYM_H : 0
        #F is the average magnitude of the B field vector..
        F : 0 

        
  ONE_HOUR_RESOLUTION:

    subdir : "{$YEAR}"
    file_glob : "omni2_h0_mrg1hr_{$YEAR}*.cdf"
    url : "https://spdf.gsfc.nasa.gov/pub/data/omni/omni_cdaweb/hourly/{$YEAR}/"
    variables:
      time_variables:
        Epoch : 0
      time_dependent:
        Dst : 0
        KP : 0
        R : 0

RBSP:

  ECT:

    L3:
      subdir : "{$SATELLITE}/{$YEAR}"
      file_glob : "rbsp{$SATELLITE}_ect-elec-L3_{$YEAR}{$MONTH}{$DAY}*.cdf"
      url : "https://rbsp-ect.newmexicoconsortium.org/data_pub/rbsp{$SATELLITE}/ECT/level3/{$YEAR}/"
      variables : 
        time_dependent:
          test : null


  EMFISIS:

    L2:

      WFR_SPECTRAL_MATRIX_DIAGONAL:

        subdir : "RBSP-{$SATELLITE_UPPER}/L2/{$YEAR}/{$MONTH}/{$DAY}"
        file_glob : "rbsp-{$SATELLITE}_WFR-spectral-matrix-diagonal_emfisis-L2_{$YEAR}{$MONTH}{$DAY}*.cdf"
        url : "https://emfisis.physics.uiowa.edu/Flight/RBSP-{$SATELLITE_UPPER}/L2/{$YEAR}/{$MONTH}/{$DAY}/"
        variables:
          time_variables:
            Epoch : 0
          time_dependent:
            WFR_bandwidth : 0
            WFR_frequencies : 0
    
    L3:

      subdir : "RBSP-{$SATELLITE}/{$YEAR}"
      file_glob : "rbsp-{$SATELLITE}_magnetometer_1sec-gse_emfisis-l3_{$YEAR}{$MONTH}{$DAY}*.cdf"
      url: "https://spdf.gsfc.nasa.gov/pub/data/rbsp/rbsp{$SATELLITE}/l3/emfisis/magnetometer/1sec/gse/{$YEAR}/"

    L4:

      WNA_SURVEY:
        subdir: "RBSP-{$SATELLITE_UPPER}/L4/{$YEAR}/{$MONTH}/{$DAY}"
        file_glob : "rbsp-{$SATELLITE}_wna-survey_emfisis-L4_{$YEAR}{$MONTH}{$DAY}*.cdf"
        url : "https://emfisis.physics.uiowa.edu/Flight/RBSP-{$SATELLITE_UPPER}/L4/{$YEAR}/{$MONTH}/{$DAY}/"
        variables:
          time_variables:
            Epoch : 0
          time_dependent:
            L : 0
            MLT : 0
            bsum : 0
            Buvw : 0
            MagLat : 0

      DENSITY:

          subdir : "RBSP-{$SATELLITE_UPPER}/L4/{$YEAR}/{$MONTH}/{$DAY}"
          file_glob : "rbsp-{$SATELLITE}_density_emfisis-L4_{$YEAR}{$MONTH}{$DAY}_v*.cdf"
          variables:
            time_variables:
              Epoch : 0
            time_dependent:
              density : 0

          
  MAGEPHEM:

    TS04D:

      subdir : "{$SATELLITE}/{$YEAR}"
      file_glob : "rbsp{$SATELLITE}_def_MagEphem_TS04D_{$YEAR}{$MONTH}{$DAY}*.h5"
      url : "https://rbsp-ect.newmexicoconsortium.org/data_pub/rbsp{$SATELLITE}/MagEphem/definitive/{$YEAR}/"
      variables:
        time_variables:
          JulianDate : 0
        
    T89D:

      subdir : "RBSP-{$SATELLITE_UPPER}/def/{$YEAR}"
      file_glob : "rbsp{$SATELLITE}_def_MagEphem_T89D_{$YEAR}{$MONTH}{$DAY}*.h5"
      url : "https://spdf.gsfc.nasa.gov/pub/data/rbsp/rbsp{$SATELLITE}/ephemeris/ect-mag-ephem/cdf/def-1min-t89d/{$YEAR}/"
      variables:
          time_variables: 
              JulianDate : 0
          time_dependent:
              Lstar : 0
              Rgeod_Height : 0
              Rgeod_LatLon : 0
              Lm_eq : 0
              EDMAG_MLAT : 0
              
              
              
              
        

  REPT:

    L2:

      subdir : "{$SATELLITE}/{$YEAR}"
      file_glob : "rbsp{$SATELLITE}_rel03_ect-rept-sci-l2_{$YEAR}{$MONTH}{$DAY}*.cdf"
      url : "https://spdf.gsfc.nasa.gov/pub/data/rbsp/rbsp{$SATELLITE}/l2/ect/rept/sectors/rel03/{$YEAR}/"
    

GOES:

  AVG:

    EPS:
      subdir : "{$SATELLITE}/{$YEAR}"
      file_glob : "{$SATELLITE}_eps_5m_{$YEAR}{$MONTH}*.nc"
      url : "https://www.ncei.noaa.gov/data/goes-space-environment-monitor/access/avg/{$YEAR}/{$MONTH}/{$SATID}/netcdf/"
      variables:
        time_variables:
          time_tag : 0
        time_dependent:
          p3_flux_ic : 0
    EPEAD:
      subdir : "{$SATELLITE}/{$YEAR}"
      file_glob : "{$SATELLITE}_epead_cpflux_5m_{$YEAR}{$MONTH}*.nc"
      url : "https://www.ncei.noaa.gov/data/goes-space-environment-monitor/access/avg/{$YEAR}/{$MONTH}/{$SATID}/netcdf/"
      variables:
        time_variables:
          time_tag : 0
        time_dependent:
          ZPGT10E : 0
          ZPGT10W : 0
    SGPS:
      V1:
        subdir : "../{$SATELLITE}/{$YEAR}"
        file_glob : "sci_sgps-l2-avg5m_{$SATELLITE}_d{$YEAR}{$MONTH}{$DAY}_v1*.nc"
        url : "https://data.ngdc.noaa.gov/platforms/solar-space-observing-satellites/goes/{$SATID}/l2/data/sgps-l2-avg5m/{$YEAR}/{$MONTH}/"
        variables:
          time_variables:
            L2_SciData_TimeStamp: 0
          time_dependent:
            AvgDiffProtonFlux : 0
            AvgIntProtonFlux: 0
          file_dependent:
            DiffProtonLowerEnergy : null
            DiffProtonUpperEnergy : null
            DiffProtonEffectiveEnergy : null
      V2:
        subdir : "../{$SATELLITE}/{$YEAR}"
        file_glob : "sci_sgps-l2-avg5m_{$SATELLITE}_d{$YEAR}{$MONTH}{$DAY}_v2*.nc"
        url : "https://data.ngdc.noaa.gov/platforms/solar-space-observing-satellites/goes/{$SATID}/l2/data/sgps-l2-avg5m/{$YEAR}/{$MONTH}/"
        variables:
          time_variables:
            L2_SciData_TimeStamp: 0
          time_dependent:
            AvgDiffProtonFlux : 0
            AvgIntProtonFlux: 0
          file_dependent:
            DiffProtonLowerEnergy : null
            DiffProtonUpperEnergy : null
            DiffProtonEffectiveEnergy : null
      V3:
        subdir : "../{$SATELLITE}/{$YEAR}"
        file_glob : "sci_sgps-l2-avg5m_{$SATELLITE}_d{$YEAR}{$MONTH}{$DAY}_v3*.nc"
        url : "https://data.ngdc.noaa.gov/platforms/solar-space-observing-satellites/goes/{$SATID}/l2/data/sgps-l2-avg5m/{$YEAR}/{$MONTH}/"
        variables:
          time_variables:
            time : 0
          time_dependent:
            AvgDiffProtonFlux : 0
            AvgIntProtonFlux: 0
          file_dependent:
            DiffProtonLowerEnergy : null
            DiffProtonUpperEnergy : null
            DiffProtonEffectiveEnergy : null

POES:
  SEM:
    L1B:
      subdir : "{$SATELLITE}/{$YEAR}"
      file_glob : "poes_{$SATELLITE}_{$YEAR}{$MONTH}{$DAY}_proc.nc"
      url : "https://www.ncei.noaa.gov/data/poes-metop-space-environment-monitor/access/l1b/v01r00/{$YEAR}/{$SATID}/"
      variables :
        time_variables:
          year : 0
          day : 0
          msec : 0
        time_dependent:
          alt : 0
          lat : 0
          lon : 0
          L_IGRF : 0
          MLT : 0
          mep_ele_tel0_flux_e1 : 0
          mep_ele_tel0_flux_e2 : 0
          meped_alpha_0_sat : 0

    L2:
      subdir : "{$SATELLITE}/{$YEAR}"
      file_glob : "poes_{$SATELLITE}_{$YEAR}{$MONTH}{$DAY}*.cdf"
      url : "https://www.ncei.noaa.gov/data/poes-metop-space-environment-monitor/access/l2/v01r00/cdf/{$YEAR}/{$SATID}/"
      variables :
        time_variables:
          EPOCH: 0
        time_dependent:
          mep0E : 0
          lValue : 0
          magLTime: 0
    
    SPDF:
      subdir : "{$SATELLITE}/{$YEAR}"
      file_glob : "{$SATELLITE}_poes-sem2_fluxes-2sec_{$YEAR}{$MONTH}{$DAY}*.cdf"
      url : "https://spdf.gsfc.nasa.gov/pub/data/noaa/{$SATELLITE}/sem2_fluxes-2sec/{$YEAR}/"

    MPE:
      subdir : "{$SATELLITE}"
      file_glob : "POES_combinedSpectrum_{$SATELLITE}_BLC_v3_{$YEAR}{$MONTH}{$DAY}.nc"
      #No url cause you need to contact Joshua Pettit to get access to this data!
      variables:
        time_variables:
          time : 0
        time_dependent:
          geogLat : 0
          geogLon : 0
          BLC_Flux: 0
          BLC_Angle: 0
          MLT : 0
          lValue : 0 
        file_dependent:
          energy : null